import type { Metadata } from "next";
import { Press_Start_2P, JetBrains_Mono, Courier_Prime } from "next/font/google";
import { SessionProvider } from "@/lib/session-context";
import { Nav } from "@/components/nav/Nav";
import { Footer } from "@/components/nav/Footer";
import "./globals.css";

const pixelFont = Press_Start_2P({
  variable: "--font-press-start",
  weight: "400",
  subsets: ["latin"],
});

const monoFont = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="es"
      className={`${pixelFont.variable} ${monoFont.variable} ${courierPrime.variable} h-full`}
    >
      <body>
        <SessionProvider>
          <div className="av-bg" aria-hidden="true">
            <div className="av-bg-grid" />
          </div>
          <div className="av-noise" aria-hidden="true" />
          <Nav />
          <main className="av-main">{children}</main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
